# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmu_ocr_detect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mmu import media_common_pb2 as mmu_dot_media__common__pb2
from mmu import common_message_pb2 as mmu_dot_common__message__pb2
from mmu import media_common_result_status_pb2 as mmu_dot_media__common__result__status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mmu_ocr_detect.proto',
  package='mmu.image',
  syntax='proto3',
  serialized_options=b'\n\037com.kuaishou.protobuf.mmu.imageB\021MmuOcrDetectProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14mmu_ocr_detect.proto\x12\tmmu.image\x1a\x16mmu/media_common.proto\x1a\x18mmu/common_message.proto\x1a$mmu/media_common_result_status.proto\"Q\n\x10OcrDetectRequest\x12 \n\x03img\x18\x01 \x03(\x0b\x32\x13.mmu.common.ImgUnit\x12\x0b\n\x03\x62iz\x18\x02 \x01(\t\x12\x0e\n\x06req_id\x18\x03 \x01(\t\"\xc6\x01\n\x11OcrDetectResponse\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.mmu.common.ResultCode\x12?\n\nocr_result\x18\x02 \x03(\x0b\x32+.mmu.image.OcrDetectResponse.OcrResultEntry\x1aJ\n\x0eOcrResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.mmu.common.FrameOcrItem:\x02\x38\x01\"5\n\x14PhotoCoverOcrRequest\x12\x10\n\x08photo_id\x18\x01 \x03(\x04\x12\x0b\n\x03\x62iz\x18\x02 \x01(\t\"\xce\x01\n\x15PhotoCoverOcrResponse\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.mmu.common.ResultCode\x12\x43\n\nocr_result\x18\x02 \x03(\x0b\x32/.mmu.image.PhotoCoverOcrResponse.OcrResultEntry\x1aJ\n\x0eOcrResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.mmu.common.FrameOcrItem:\x02\x38\x01\"=\n\x0ePhotoOcrResult\x12+\n\tframe_ocr\x18\x01 \x03(\x0b\x32\x18.mmu.common.FrameOcrItem\"\xc5\x01\n\x10PhotoOcrResponse\x12$\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x16.mmu.common.ResultCode\x12>\n\nocr_result\x18\x02 \x03(\x0b\x32*.mmu.image.PhotoOcrResponse.OcrResultEntry\x1aK\n\x0eOcrResultEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.mmu.image.PhotoOcrResult:\x02\x38\x01\x32\x81\x02\n\x13MmuOcrDetectService\x12\x46\n\tOcrDetect\x12\x1b.mmu.image.OcrDetectRequest\x1a\x1c.mmu.image.OcrDetectResponse\x12U\n\x10GetPhotoCoverOcr\x12\x1f.mmu.image.PhotoCoverOcrRequest\x1a .mmu.image.PhotoCoverOcrResponse\x12K\n\x0bGetPhotoOcr\x12\x1f.mmu.image.PhotoCoverOcrRequest\x1a\x1b.mmu.image.PhotoOcrResponseB6\n\x1f\x63om.kuaishou.protobuf.mmu.imageB\x11MmuOcrDetectProtoP\x01\x62\x06proto3'
  ,
  dependencies=[mmu_dot_media__common__pb2.DESCRIPTOR,mmu_dot_common__message__pb2.DESCRIPTOR,mmu_dot_media__common__result__status__pb2.DESCRIPTOR,])




_OCRDETECTREQUEST = _descriptor.Descriptor(
  name='OcrDetectRequest',
  full_name='mmu.image.OcrDetectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='mmu.image.OcrDetectRequest.img', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='biz', full_name='mmu.image.OcrDetectRequest.biz', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='req_id', full_name='mmu.image.OcrDetectRequest.req_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=204,
)


_OCRDETECTRESPONSE_OCRRESULTENTRY = _descriptor.Descriptor(
  name='OcrResultEntry',
  full_name='mmu.image.OcrDetectResponse.OcrResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mmu.image.OcrDetectResponse.OcrResultEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mmu.image.OcrDetectResponse.OcrResultEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=405,
)

_OCRDETECTRESPONSE = _descriptor.Descriptor(
  name='OcrDetectResponse',
  full_name='mmu.image.OcrDetectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mmu.image.OcrDetectResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ocr_result', full_name='mmu.image.OcrDetectResponse.ocr_result', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_OCRDETECTRESPONSE_OCRRESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=405,
)


_PHOTOCOVEROCRREQUEST = _descriptor.Descriptor(
  name='PhotoCoverOcrRequest',
  full_name='mmu.image.PhotoCoverOcrRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='photo_id', full_name='mmu.image.PhotoCoverOcrRequest.photo_id', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='biz', full_name='mmu.image.PhotoCoverOcrRequest.biz', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=460,
)


_PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY = _descriptor.Descriptor(
  name='OcrResultEntry',
  full_name='mmu.image.PhotoCoverOcrResponse.OcrResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mmu.image.PhotoCoverOcrResponse.OcrResultEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mmu.image.PhotoCoverOcrResponse.OcrResultEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=669,
)

_PHOTOCOVEROCRRESPONSE = _descriptor.Descriptor(
  name='PhotoCoverOcrResponse',
  full_name='mmu.image.PhotoCoverOcrResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mmu.image.PhotoCoverOcrResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ocr_result', full_name='mmu.image.PhotoCoverOcrResponse.ocr_result', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=669,
)


_PHOTOOCRRESULT = _descriptor.Descriptor(
  name='PhotoOcrResult',
  full_name='mmu.image.PhotoOcrResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_ocr', full_name='mmu.image.PhotoOcrResult.frame_ocr', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=671,
  serialized_end=732,
)


_PHOTOOCRRESPONSE_OCRRESULTENTRY = _descriptor.Descriptor(
  name='OcrResultEntry',
  full_name='mmu.image.PhotoOcrResponse.OcrResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mmu.image.PhotoOcrResponse.OcrResultEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mmu.image.PhotoOcrResponse.OcrResultEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=857,
  serialized_end=932,
)

_PHOTOOCRRESPONSE = _descriptor.Descriptor(
  name='PhotoOcrResponse',
  full_name='mmu.image.PhotoOcrResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='mmu.image.PhotoOcrResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ocr_result', full_name='mmu.image.PhotoOcrResponse.ocr_result', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PHOTOOCRRESPONSE_OCRRESULTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=735,
  serialized_end=932,
)

_OCRDETECTREQUEST.fields_by_name['img'].message_type = mmu_dot_media__common__pb2._IMGUNIT
_OCRDETECTRESPONSE_OCRRESULTENTRY.fields_by_name['value'].message_type = mmu_dot_common__message__pb2._FRAMEOCRITEM
_OCRDETECTRESPONSE_OCRRESULTENTRY.containing_type = _OCRDETECTRESPONSE
_OCRDETECTRESPONSE.fields_by_name['code'].enum_type = mmu_dot_media__common__result__status__pb2._RESULTCODE
_OCRDETECTRESPONSE.fields_by_name['ocr_result'].message_type = _OCRDETECTRESPONSE_OCRRESULTENTRY
_PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY.fields_by_name['value'].message_type = mmu_dot_common__message__pb2._FRAMEOCRITEM
_PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY.containing_type = _PHOTOCOVEROCRRESPONSE
_PHOTOCOVEROCRRESPONSE.fields_by_name['code'].enum_type = mmu_dot_media__common__result__status__pb2._RESULTCODE
_PHOTOCOVEROCRRESPONSE.fields_by_name['ocr_result'].message_type = _PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY
_PHOTOOCRRESULT.fields_by_name['frame_ocr'].message_type = mmu_dot_common__message__pb2._FRAMEOCRITEM
_PHOTOOCRRESPONSE_OCRRESULTENTRY.fields_by_name['value'].message_type = _PHOTOOCRRESULT
_PHOTOOCRRESPONSE_OCRRESULTENTRY.containing_type = _PHOTOOCRRESPONSE
_PHOTOOCRRESPONSE.fields_by_name['code'].enum_type = mmu_dot_media__common__result__status__pb2._RESULTCODE
_PHOTOOCRRESPONSE.fields_by_name['ocr_result'].message_type = _PHOTOOCRRESPONSE_OCRRESULTENTRY
DESCRIPTOR.message_types_by_name['OcrDetectRequest'] = _OCRDETECTREQUEST
DESCRIPTOR.message_types_by_name['OcrDetectResponse'] = _OCRDETECTRESPONSE
DESCRIPTOR.message_types_by_name['PhotoCoverOcrRequest'] = _PHOTOCOVEROCRREQUEST
DESCRIPTOR.message_types_by_name['PhotoCoverOcrResponse'] = _PHOTOCOVEROCRRESPONSE
DESCRIPTOR.message_types_by_name['PhotoOcrResult'] = _PHOTOOCRRESULT
DESCRIPTOR.message_types_by_name['PhotoOcrResponse'] = _PHOTOOCRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OcrDetectRequest = _reflection.GeneratedProtocolMessageType('OcrDetectRequest', (_message.Message,), {
  'DESCRIPTOR' : _OCRDETECTREQUEST,
  '__module__' : 'mmu_ocr_detect_pb2'
  # @@protoc_insertion_point(class_scope:mmu.image.OcrDetectRequest)
  })
_sym_db.RegisterMessage(OcrDetectRequest)

OcrDetectResponse = _reflection.GeneratedProtocolMessageType('OcrDetectResponse', (_message.Message,), {

  'OcrResultEntry' : _reflection.GeneratedProtocolMessageType('OcrResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _OCRDETECTRESPONSE_OCRRESULTENTRY,
    '__module__' : 'mmu_ocr_detect_pb2'
    # @@protoc_insertion_point(class_scope:mmu.image.OcrDetectResponse.OcrResultEntry)
    })
  ,
  'DESCRIPTOR' : _OCRDETECTRESPONSE,
  '__module__' : 'mmu_ocr_detect_pb2'
  # @@protoc_insertion_point(class_scope:mmu.image.OcrDetectResponse)
  })
_sym_db.RegisterMessage(OcrDetectResponse)
_sym_db.RegisterMessage(OcrDetectResponse.OcrResultEntry)

PhotoCoverOcrRequest = _reflection.GeneratedProtocolMessageType('PhotoCoverOcrRequest', (_message.Message,), {
  'DESCRIPTOR' : _PHOTOCOVEROCRREQUEST,
  '__module__' : 'mmu_ocr_detect_pb2'
  # @@protoc_insertion_point(class_scope:mmu.image.PhotoCoverOcrRequest)
  })
_sym_db.RegisterMessage(PhotoCoverOcrRequest)

PhotoCoverOcrResponse = _reflection.GeneratedProtocolMessageType('PhotoCoverOcrResponse', (_message.Message,), {

  'OcrResultEntry' : _reflection.GeneratedProtocolMessageType('OcrResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY,
    '__module__' : 'mmu_ocr_detect_pb2'
    # @@protoc_insertion_point(class_scope:mmu.image.PhotoCoverOcrResponse.OcrResultEntry)
    })
  ,
  'DESCRIPTOR' : _PHOTOCOVEROCRRESPONSE,
  '__module__' : 'mmu_ocr_detect_pb2'
  # @@protoc_insertion_point(class_scope:mmu.image.PhotoCoverOcrResponse)
  })
_sym_db.RegisterMessage(PhotoCoverOcrResponse)
_sym_db.RegisterMessage(PhotoCoverOcrResponse.OcrResultEntry)

PhotoOcrResult = _reflection.GeneratedProtocolMessageType('PhotoOcrResult', (_message.Message,), {
  'DESCRIPTOR' : _PHOTOOCRRESULT,
  '__module__' : 'mmu_ocr_detect_pb2'
  # @@protoc_insertion_point(class_scope:mmu.image.PhotoOcrResult)
  })
_sym_db.RegisterMessage(PhotoOcrResult)

PhotoOcrResponse = _reflection.GeneratedProtocolMessageType('PhotoOcrResponse', (_message.Message,), {

  'OcrResultEntry' : _reflection.GeneratedProtocolMessageType('OcrResultEntry', (_message.Message,), {
    'DESCRIPTOR' : _PHOTOOCRRESPONSE_OCRRESULTENTRY,
    '__module__' : 'mmu_ocr_detect_pb2'
    # @@protoc_insertion_point(class_scope:mmu.image.PhotoOcrResponse.OcrResultEntry)
    })
  ,
  'DESCRIPTOR' : _PHOTOOCRRESPONSE,
  '__module__' : 'mmu_ocr_detect_pb2'
  # @@protoc_insertion_point(class_scope:mmu.image.PhotoOcrResponse)
  })
_sym_db.RegisterMessage(PhotoOcrResponse)
_sym_db.RegisterMessage(PhotoOcrResponse.OcrResultEntry)


DESCRIPTOR._options = None
_OCRDETECTRESPONSE_OCRRESULTENTRY._options = None
_PHOTOCOVEROCRRESPONSE_OCRRESULTENTRY._options = None
_PHOTOOCRRESPONSE_OCRRESULTENTRY._options = None

_MMUOCRDETECTSERVICE = _descriptor.ServiceDescriptor(
  name='MmuOcrDetectService',
  full_name='mmu.image.MmuOcrDetectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=935,
  serialized_end=1192,
  methods=[
  _descriptor.MethodDescriptor(
    name='OcrDetect',
    full_name='mmu.image.MmuOcrDetectService.OcrDetect',
    index=0,
    containing_service=None,
    input_type=_OCRDETECTREQUEST,
    output_type=_OCRDETECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPhotoCoverOcr',
    full_name='mmu.image.MmuOcrDetectService.GetPhotoCoverOcr',
    index=1,
    containing_service=None,
    input_type=_PHOTOCOVEROCRREQUEST,
    output_type=_PHOTOCOVEROCRRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPhotoOcr',
    full_name='mmu.image.MmuOcrDetectService.GetPhotoOcr',
    index=2,
    containing_service=None,
    input_type=_PHOTOCOVEROCRREQUEST,
    output_type=_PHOTOOCRRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MMUOCRDETECTSERVICE)

DESCRIPTOR.services_by_name['MmuOcrDetectService'] = _MMUOCRDETECTSERVICE

# @@protoc_insertion_point(module_scope)
